### ISSUE TITLE
FNE Monitor displays actual frequencies instead of effective frequencies

### ISSUE THREAD

**Issue by drsn0w** [gatekeep/dvmfne#7]
![image](https://user-images.githubusercontent.com/1100374/154402200-40fcf63d-0bbe-4492-b85a-c87b257ecb0f.png)

Date and time bug was found: 02/16/2022 2150 CST
Priority of bug: Low
Detailed explanation of bug: RX Frequency is shown as 147.00626 Mhz, rounding up from 147006256hz which is the RX frequency before the RX Tuning Offset is applied.
How to recreate bug: Join the FNE as a master system with a TX or RX offset applied and it will show the incorrect value

**Comment by jelimoore** [comment]
Hi, if I'm understanding this correctly, are you saying that the frequency reported in the FNE is the frequency of the hotspot before calibration (i.e. what frequency it should transmit on) or the frequency of the hotspot after calibration (i.e. the desired frequency +/- the frequency offset)?

**Comment by drsn0w** [comment]
> Hi, if I'm understanding this correctly, are you saying that the frequency reported in the FNE is the frequency of the hotspot before calibration (i.e. what frequency it should transmit on) or the frequency of the hotspot after calibration (i.e. the desired frequency +/- the frequency offset)?

That's correct

**Comment by jelimoore** [comment]
Which one does it display currently, and which one are you expecting it to display?

**Comment by drsn0w** [comment]
I'm showing it displaying the frequency before calibration, and I'd expect it to show the frequency after calibration, but I might be wrong about that.

**Comment by jelimoore** [comment]
Closing as wontfix per Discord discussion
