### ISSUE TITLE
FNE Wide Command issue

### ISSUE THREAD

**Issue by carcarjg** [gatekeep/dvmfne#8]
Add Ability to issue commands to all nodes on FNE server VS specific nodes.

**Comment by gatekeep** [comment]
This already exists. If you want to send a command to *all* nodes connected to a FNE; on the Remote Command screen in fnemon; simply select the global checkbox. The command should be then sent to all selected nodes.

If this is not working then this is a bug.

![Image 32](https://user-images.githubusercontent.com/1149277/155358481-e87be237-8554-4aa9-abb1-55294f041e0c.png)

**Comment by carcarjg** [comment]
Yea, That just causes the top checkbox to be checked.

**Comment by gatekeep** [comment]
Should be selecting all the entries; @jelimoore maybe this is a bug; however it works on my FNE.

**Comment by carcarjg** [comment]
Fixed in the new FNE
